var letraA = document.getElementById("A");
var letraB = document.getElementById("B");
var letraC = document.getElementById("C");
var letraD = document.getElementById("D");
var letraE = document.getElementById("E");
var letraF = document.getElementById("F");
var letraG = document.getElementById("G");
var letraH = document.getElementById("H");
var letraI = document.getElementById("I");
var letraJ = document.getElementById("J");
var letraK = document.getElementById("K");
var letraL = document.getElementById("L");
var letraM = document.getElementById("M");
var letraN = document.getElementById("N");
var letraO = document.getElementById("O");
var letraP = document.getElementById("P");
var letraQ = document.getElementById("Q");
var letraR = document.getElementById("R");
var letraS = document.getElementById("S");
var letraT = document.getElementById("T");
var letraU = document.getElementById("U");
var letraV = document.getElementById("V");
var letraW = document.getElementById("W");
var letraX = document.getElementById("X");
var letraY = document.getElementById("Y");
var letraZ = document.getElementById("Z");
var div1 = document.getElementsByClassName("A")    
var div2 = document.getElementsByClassName("B")    
var div3 = document.getElementsByClassName("C")    
var div4 = document.getElementsByClassName("D")    
var div5 = document.getElementsByClassName("E")    
var div6 = document.getElementsByClassName("F")    
var div7 = document.getElementsByClassName("G")    
var div8 = document.getElementsByClassName("H")    
var div9 = document.getElementsByClassName("I")    
var div10 = document.getElementsByClassName("J")
var div11 = document.getElementsByClassName("K")
var div12 = document.getElementsByClassName("L")
var div13 = document.getElementsByClassName("M")
var div14 = document.getElementsByClassName("N")
var div15 = document.getElementsByClassName("O")
var div16 = document.getElementsByClassName("P")
var div17 = document.getElementsByClassName("Q")
var div18 = document.getElementsByClassName("R")
var div19 = document.getElementsByClassName("S")
var div20 = document.getElementsByClassName("T")
var div21 = document.getElementsByClassName("U")
var div22 = document.getElementsByClassName("V")
var div23 = document.getElementsByClassName("W")
var div24 = document.getElementsByClassName("X")
var div25 = document.getElementsByClassName("Y")
var div26 = document.getElementsByClassName("Z")

letraT.onclick = function letraT(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraA.onclick = function letraA(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraB.onclick = function letraB(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraC.onclick = function letraC(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraD.onclick = function letraD(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraE.onclick = function letraE(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraF.onclick = function letraF(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraG.onclick = function letraG(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraH.onclick = function letraH(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraI.onclick = function letraI(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraJ.onclick = function letraJ(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
    }
letraK.onclick = function letraK(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraL.onclick = function letraL(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraM.onclick = function letraM(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
                }
letraN.onclick = function letraN(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraO.onclick = function letraO(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraP.onclick = function letraP(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraQ.onclick = function letraQ(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraR.onclick = function letraR(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraS.onclick = function letraS(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraU.onclick = function letraU(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraV.onclick = function letraV(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraW.onclick = function letraW(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraX.onclick = function letraX(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraY.onclick = function letraY(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Z";}})
}
letraZ.onclick = function letraZ(){
$.each(item, function(i, val) {if (i > 15) {val.style.display = 'inline'}});
$.each(div1, function(i, val) {if (typeof(val) != "undefined"){val.className = "display_none A";}})
$.each(div2, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none B";}})
$.each(div3, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none C";}})
$.each(div4, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none D";}})
$.each(div5, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none E";}})
$.each(div6, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none F";}})
$.each(div7, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none G";}})
$.each(div8, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none H";}})
$.each(div9, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none I";}})
$.each(div10, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none J";}})
$.each(div11, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none K";}})
$.each(div12, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none L";}})
$.each(div13, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none M";}})
$.each(div14, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none N";}})
$.each(div15, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none O";}})
$.each(div16, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none P";}})
$.each(div17, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Q";}})
$.each(div18, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none R";}})
$.each(div19, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none S";}})
$.each(div20, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none T";}})
$.each(div21, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none U";}})
$.each(div22, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none V";}})
$.each(div23, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none W";}})
$.each(div24, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none X";}})
$.each(div25, function(i, val){if (typeof(val) != "undefined"){val.className = "display_none Y";}})
$.each(div26, function(i, val){if (typeof(val) != "undefined"){val.className = "col-sm-6 col-d-4 col-lg-3 itemloopLojas Z";}})
}                                          